spring:
  datasource:
    username: test
    password: 12345678
    url: jdbc:mysql://localhost:3306/goodnight2022?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.ym.163.com
    username: mail@xxx.com
    password: xxx
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
      mail.smtp.connectiontimeout: 10000
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 994
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379

server:
  port: 1090
  address: 127.0.0.1
  website: http://localhost